name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80e83e09a19bbac94c027e96e0023ce25dddf61b0f86df2df35bd6a6f064c623"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
