name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.0-pre24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f225311537cdc5aa8cfc84fa0ab85c45585e20fb9c4d29fcc1786bf3cbd4f8e"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
