name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04714bf698f1ebebece9c764f79ea40298bccaf516f267f737f4bed4baccd7d2"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
