name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a8d48ecc52d733a848b16b17fb04ecb2e32e4229403229a41ad116f47bfd89d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
