name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15d0b4656820c3fc02e39a32e50017e55b382f11a574e17bf417fdb17edd998e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
