name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.0-pre32"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b60dc82873904590554d40da76925f5265f90d7bb53e4f44d436a225cd2cb159"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
