name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f310509a393147bb06f88e0540095117bd5acb74f2a69f912873d9f0ba0f04a9"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
