name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d52932389e8ec5ba42fe0f2abfd83b488437482400d89e7bd24f06b925ae81e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
