name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.0-pre13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40db15123a635840d36f33dc4fab693c581cca90dfbf8559c7308f2d604e65f7"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
