name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c49d828d0e4091e69ff79ff2febf89f47a29aabce1038d31ce94c41ac41944d9"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
