name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e24530a0d7d513805b3e1f79ae651123fab542f2e87e71912a7ce136f6b54ef3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
