name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.8.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0c0803dba6c7e638ca584a6bced7c200da027d630356529d26af9b8efa8d0eb"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
