name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.0-pre9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4a1ba2537c0e0ae8b711ac89f89267703fc9d87cc8b1b387bd339b6d4a808e1"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
