name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc2502db83cafcf0b6a5d789ae07292ebac91b049d56756351ffaf446ebc5266"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
