name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85b0ad0b55cc75b76336d477ed308640d264bf6713d47928c891e3b3504b0f5e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
