name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.0-pre11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4b9592c17bcd44237b06bebf066bc8c5bf1c9d2e3c8358f231401fa41c50d69"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
