name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a72d7b5e831831dac5aadc02b765bf082792e59a8a17f7e565676e1c679f32c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
