name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9b40d10c45ab41617594d83c55e05e5631f7b85e162d200e27355c94b6cc703"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
