name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6f397305b418bf34f5b17f4631e911b9e1ac11a02214214e7c51f1fe8495ca1"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
