name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6052a63de0204f5063e2640cbafef297eafdbf4886a388996dfb2b96faa22ac"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
