name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "decdec1862e45e4a4e39a3d606a320c229d0082a21098f457e2ccc0e69327b03"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
