name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e74f593f281e1f55c54077d15208cea0700d3b6a2fba3512294ceefa3488d652"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
