name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.599"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3f491e848c87cdfbe29ebba20fe7a618b6726bfc776a50d1359a68ba96b2954"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
