name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.0.140"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6ca1dd7ee136a21d2443f590ec5557201d12c04591c83e423f52894792f3324"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
