name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efc151b35b6f363e0b629d692da5a38efa148738cd094de5e3ff8a096112a577"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
