name = "Shadow Wizards Money Gang"
author = "SantyPlays,Cybercat555"
version = "0.1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "370f8a8edc3385b4dd50a7801842bad9632af83414af32bf6dc84ba7cc8abf7b"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
unsup = "0.2.3"

[options]
acceptable-game-versions = ["1.20.1"]
