[client.pv.activation]
proximity = "Zbliżeniowy"

[server.pv.command.list]
empty = "brak graczy z zainstalowanym Plasmo Voice"
message = "Klienci (%1$s/%2$s): %3$s"

[server.pv.command.mute]
already_muted = "%s jest już wyciszony"
permanently_muted = "%1$s jest permanentnie wyciszony. Powód: %2$s"
temporarily_muted = "Wyciszono %1$s %2$s. Powód: %3$s"
usage = "Użycie: /vmute <gracz> [długość] [powód]"

[server.pv.command.mute_list]
empty = "Żadni gracze nie są wyciszeni"
entry = "%1$s, wygasa: %2$s. Powód: %3$s"
entry_muted_by = "%1$s wyciszony przez %2$s, wygasa: %3$s. Powód: %4$s"
expiration_date = "dd.MM.yyyy"
expiration_time = "HH:mm:ss"
expire_at = "%1$s o %2$s"
header = "Wyciszeni gracze:"
never_expires = "nigdy"

[server.pv.command.reconnect]
message = "Pakiety ponownego połączenia wysłane"

[server.pv.command.reload]
message = "Przeładowano konfigurację"

[server.pv.command.unmute]
not_muted = "%s nie jest wyciszony"
unmuted = "Odciszono %s"
usage = "Użycie: /vunmute <gracz>"

[server.pv.error]
mod_missing_kick_message = """
Przepraszamy, musisz zainstalować modyfikację Plasmo Voice, aby grać na tym serwerze.
Pobierz tutaj: https://modrinth.com/plugin/plasmo-voice"""
no_permissions = "&cPrzepraszamy, lecz nie posiadasz permisji, aby wykonać to polecenie. Skontaktuj się z administratorami serwera, jeżeli uważasz, że jest to błąd."
player_not_found = "Gracz nie odnaleziony"
player_only_command = "Tylko gracze mogą wykonywać to polecenie"
version_not_supported = "Przepraszamy, Twoja wersja Plasmo Voice nie jest wspierana na tym serwerze. %s"
version_not_supported_click = "Pobierz wspieraną wersję"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "nie określono"
permanently_muted = "Zostałeś permanentnie wyciszony. Powód %s"
temporarily_muted = "Zostałeś wyciszony %1$s. Powód: %2$s"
unmuted = "Zostałeś odciszony"

[server.pv.mutes.durations]
days = "na %s d"
hours = "na %s godz"
minutes = "na %s min"
seconds = "na %s s"
weeks = "na %s tyg"
