[client.pv.activation]
proximity = "Proximidade"

[server.pv.command.list]
empty = "nenhum jogador com Plasmo Voice instalado"
message = "Clientes (%1$s/%2$s): %3$s"

[server.pv.command.mute]
already_muted = "%s já está silenciado"
permanently_muted = "%1$s está silenciado permanentemente. Motivo: %2$s"
temporarily_muted = "Silenciado %1$s %2$s. Motivo: %3$s"
usage = "Uso: /vmute <player> [duration] [reason]"

[server.pv.command.mute_list]
empty = "Nenhum jogador está silenciado"
entry = "%1$s, expira em: %2$s. Motivo: %3$s"
entry_muted_by = "%1$s silenciado por %2$s, expira em %3$s. Motivo: %4$s"
expiration_date = "dd/MM/yyyy"
expiration_time = "HH:mm:ss"
expire_at = "%1$s em %2$s"
header = "Jogadores silenciados:"
never_expires = "nunca"

[server.pv.command.reconnect]
message = "Pacote de reconexão enviado"

[server.pv.command.reload]
message = "Configuração recarregada"

[server.pv.command.unmute]
not_muted = "%s não está silenciado"
unmuted = "Desmutou %s"
usage = "Uso: /vmute <player>"

[server.pv.error]
mod_missing_kick_message = """
Desculpe, você precisa instalar o Plasmo Voice mod para jogar neste servidor.
Baixe aqui: https://modrinth.com/plugin/plasmo-voice"""
no_permissions = "&cDesculpe, mas você não tem permissão para executar este comando. Por favor contate os administradores do servidor se você acredita que isto é um erro."
player_not_found = "Jogador não encontrado"
player_only_command = "&cApenas jogadores podem usar esse comando"
version_not_supported = "Desculpe, sua versão do Plasmo Voice não é suportada neste servidor. %s"
version_not_supported_click = "Baixar versão suportada"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "não especificado"
permanently_muted = "Você foi silenciado permanentemente. Motivo: %s"
temporarily_muted = "Você foi silenciado %1$s. Motivo: %2$s"
unmuted = "Você foi desmutado"

[server.pv.mutes.durations]
days = "por %s d"
hours = "por %s h"
minutes = "por %s min"
seconds = "por %s seg"
weeks = "para %s sem"
