[server.pv.error]
mod_missing_kick_message = "Désolé, vous devez installer le mod Plasmo Voice pour jouer sur ce serveur.\nTélécharger ici : https://modrinth.com/plugin/plasmo-voice"
player_not_found = "Joueur introuvable"
version_not_supported = "Désolé, votre version Plasmo Voice n'est pas prise en charge sur ce serveur. %s"
player_only_command = "Seuls les joueurs peuvent exécuter cette commande"
version_not_supported_click = "Téléchargez la version supportée"
no_permissions = "%cDésolé, mais vous n'êtes pas autorisé à exécuter cette commande. Veuillez contacter les administrateurs du serveur si vous pensez que c'est une erreur."
version_not_supported_hover = "%s"
[server.pv.mutes]
unmuted = "Vous n'êtes plus muet"
empty_reason = "non spécifié"
permanently_muted = "Vous avez été rendu muet de façon permanente. Raison : %s"
temporarily_muted = "Vous avez été rendu muet %1$s. Raison : %2$s"

[server.pv.mutes.durations]
hours = "pour %s heures"
seconds = "pour %s secondes"
weeks = "pour %s semaines"
minutes = "pour %s minutes"
days = "pour %s jours"
[server.pv.command.mute_list]
expiration_time = "HH:mm:ss"
never_expires = "jamais"
expiration_date = "dd.MM.yyyy"
empty = "Aucun joueur n'est muet"
entry_muted_by = "%1$s rendu muet par %2$s, expire : %3$s. Raison : %4$s"
entry = "%1$s, expire : %2$s. Raison : %3$s"
header = "Joueurs muets :"
expire_at = "%1$s à %2$s"
[server.pv.command.mute]
already_muted = "%s est déjà muet"
usage = "Utilisation: /vmute <joueur> [durée] [raison]"
permanently_muted = "%1$s est rendu muet en permanence. Raison : %2$s"
temporarily_muted = "%1$s rendu muet. Raison : %3$s"
[server.pv.command.list]
message = "Clients (%1$s/%2$s) : %3$s"
empty = "aucun joueur avec Plasmo Voice installé"
[server.pv.command.reconnect]
message = "Paquet de reconnexion envoyé"
[server.pv.command.reload]
message = "Configuration rechargée"
[server.pv.command.unmute]
unmuted = "%s n'est plus muet."
usage = "Utilisation : /vunmute <joueur>"
not_muted = "%s n'est pas muet"
[client.pv.activation]
proximity = "Proximité"
