[server.pv.error]
mod_missing_kick_message = "Üzgünüz, bu sunucuda oynamak için Plasmo Voice modunu yüklemeniz gerekiyor.\nBuradan indirin: https://modrinth.com/plugin/plasmo-voice"
player_not_found = "Öyle bir oyuncu yok"
version_not_supported = "Üzgünüz, Plasmo Voice sürümünüz bu sunucuda desteklenmiyor. %s"
player_only_command = "Bu komutu yalnızca oyuncu çalıştırabilir"
version_not_supported_click = "Desteklenen sürümü indirin"
no_permissions = "Üzgünüm, ancak bu komutu gerçekleştirmek için izniniz yok. Bunun hatalı olduğunu düşünüyorsanız lütfen sunucu yöneticileriyle iletişime geçin."
version_not_supported_hover = "%s"
[server.pv.mutes]
empty_reason = "belirtilmemiş"
temporarily_muted = "Sesiniz moderatör tarafından devre dışı bırakıldı: %1$s. Sebep: %2$s"
