# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				panda = true
				bee = true
				axolotl = true
				egg = true
				zoglin = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				husk = true
				bat = true
				frog = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				goat = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				mooshroom = true
				glow_squid = true
				warden = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				cat = true
				zombie = true
				guardian = true
				sheep = true
				player = true
				pufferfish = true
				illusioner = true
				potion = true
				trident = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				boat = true
				small_fireball = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true

			[light_sources.settings.entities.fallingtrees]
				tree = true

			[light_sources.settings.entities.paladins]
				barrier = true

			[light_sources.settings.entities.uselessreptile]
				lightning_chaser = true
				lightning_breath = true
				moleclaw = true
				wyvern_projectile = true
				river_pikehorn = true
				wyvern = true
				acid_blast = true

			[light_sources.settings.entities.xercapaint]
				easel = true

			[light_sources.settings.entities.spell_engine]
				spell_projectile = true
				spell_area_effect = true

			[light_sources.settings.entities.goodending]
				firefly_swarm = true
				woodpecker = true
				boat = true

			[light_sources.settings.entities.enderzoology]
				fallen_mount = true
				owl = true
				wither_witch = true
				wither_cat = true
				owl_egg = true
				fallen_knight = true
				infested_zombie = true
				enderminy = true
				concussion_creeper = true

			[light_sources.settings.entities.niftycarts]
				supply_cart = true
				animal_cart = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.arcanuscontinuum]
				opossum = true
				wizard = true

			[light_sources.settings.entities.mythicmobs]
				mushroom_thing = true

			[light_sources.settings.entities.mobs_of_mythology]
				kobold_warrior = true
				sporeling = true
				kobold = true
				chupacabra = true

			[light_sources.settings.entities.shadow-wizards]
				spider_scorpion = true
				zotz = true
				firebomb = true
				small_spider_scorpion = true
				manticore = true
				fallen_undead = true
				gas = true
				ghoul = true
				fallen_horse = true
				rous = true
				cupcake = true

			[light_sources.settings.entities.faunus]
				leech = true
				cocoa_bean_projectile = true
				capuchin = true
				iguana = true
				piranha = true
				yacare = true
				crayfish = true
				songbird = true
				arapaima = true

			[light_sources.settings.entities.illagerinvasion]
				skull_bolt = true
				sorcerer = true
				archivist = true
				provoker = true
				basher = true
				necromancer = true
				firecaller = true
				invoker = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				robin = true
				boar = true
				dragonfly = true
				duck_egg = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				zebra = true
				rattlesnake = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				lizard_tail = true
				elephant = true
				finch = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				giant = true
				cerberus = true
				cursed_armor = true
				tank = true

			[light_sources.settings.entities.bombastic_crystals]
				shattering_crystals = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.frostiful]
				frost_tipped_arrow = true

			[light_sources.settings.entities.caligo]
				strow = true
				deep_strow = true
				coppice = true

			[light_sources.settings.entities.dungeonnowloading]
				spawner_carrier = true
				chaos_spawner = true
				great_experience_bottle = true

			[light_sources.settings.entities.yungscavebiomes]
				ice_cube = true

